"use client";

import { useState } from "react";
import { Avatar, SectionHeading, StatusBadge } from "./app-shell";
import { Icon } from "./icons";

export default function MentorshipBoard() {
  const [tab, setTab] = useState("overview");
  const [complete, setComplete] = useState(false);

  return <>
    <div className="relationship-hero"><div className="relationship-identity"><div className="avatar-stack"><Avatar initials="AS" tone="amber" size="lg" /><span className="connection-line" /><Avatar initials="MC" tone="rose" size="lg" /></div><div><span className="section-eyebrow">Since 12 August 2026</span><h1>Build, reflect, <em>repeat.</em></h1><p>A focused space for the work between the conversations.</p></div></div><div className="relationship-status"><StatusBadge>Active mentorship</StatusBadge><span>Next check-in in 4 days</span></div></div>
    <div className="relationship-profile"><div className="person-summary"><Avatar initials="MC" tone="rose" size="md" /><div><strong>Meera Chawla</strong><span>Product Designer · Figma</span></div><span className="verified-chip"><Icon name="shield" size={12} /> Verified alumna</span></div><div className="relationship-actions"><button className="button button-outline" type="button"><Icon name="message" size={16} /> Message Meera</button><button aria-label="More relationship options" className="plain-icon-button" type="button"><Icon name="more" size={18} /></button></div></div>

    <div className="tab-bar" role="tablist" aria-label="Mentorship sections">{[{ id: "overview", label: "Overview" }, { id: "sessions", label: "Sessions", count: "4" }, { id: "goals", label: "Goals & actions", count: "2" }, { id: "notes", label: "Shared notes" }].map((item) => <button aria-selected={tab === item.id} className={`tab-button ${tab === item.id ? "is-active" : ""}`} key={item.id} onClick={() => setTab(item.id)} role="tab" type="button">{item.label}{item.count ? <span>{item.count}</span> : null}</button>)}</div>

    {tab === "overview" ? <div className="relationship-grid"><section className="panel timeline-panel"><SectionHeading eyebrow="Your journey" title="A little momentum goes a long way" action={<button className="text-link" type="button">View timeline <Icon name="arrow" size={15} /></button>} /><div className="timeline"><div className="timeline-item is-complete"><span className="timeline-dot"><Icon name="check" size={13} /></span><div><strong>First conversation</strong><span>12 Aug 2026 · Career direction and context</span></div><StatusBadge>Complete</StatusBadge></div><div className="timeline-item is-complete"><span className="timeline-dot"><Icon name="check" size={13} /></span><div><strong>Define a portfolio goal</strong><span>19 Aug 2026 · One clear outcome for this semester</span></div><StatusBadge>Complete</StatusBadge></div><div className="timeline-item is-next"><span className="timeline-dot"><Icon name="calendar" size={13} /></span><div><strong>Portfolio review &amp; next steps</strong><span>28 Sep 2026 · 6:00 PM · Alma video room</span></div><StatusBadge tone="amber">Next up</StatusBadge></div></div></section><section className="panel action-panel"><SectionHeading eyebrow="Your next actions" title="Before you meet" /><div className={`action-card ${complete ? "is-done" : ""}`}><button aria-label={complete ? "Mark action incomplete" : "Mark action complete"} className="action-check" onClick={() => setComplete(!complete)} type="button"><Icon name="check" size={14} /></button><div><strong>Share your latest portfolio link</strong><span>Due 27 Sep · Added by you</span></div></div><div className="action-card"><button aria-label="Mark action complete" className="action-check" type="button"><Icon name="check" size={14} /></button><div><strong>Bring one product case study question</strong><span>Due 28 Sep · Added by Meera</span></div></div><button className="add-action" type="button"><span>+</span> Add an action</button></section></div> : <div className="panel tab-placeholder"><Icon name={tab === "sessions" ? "calendar" : tab === "goals" ? "flag" : "message"} size={24} /><h2>{tab === "sessions" ? "Four thoughtful sessions so far." : tab === "goals" ? "Two goals, with clear next steps." : "Keep the useful context together."}</h2><p>This demo view is ready for the next layer of relationship detail: session records, measurable goals, and private notes.</p><button className="button button-outline" type="button">Add a note <Icon name="arrow" size={15} /></button></div>}
  </>;
}
