import { AppShell, SectionHeading, StatusBadge } from "../_components/app-shell";
import { Icon } from "../_components/icons";

const bars = [38, 52, 46, 67, 59, 74, 82, 78, 89, 85, 96, 91];
const months = ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"];

export default function AnalyticsPage() {
  return <AppShell active="analytics" eyebrow="Alumni Relations · Programme view" title="See what is working"><div className="page-intro analytics-intro"><div><span className="section-eyebrow">Semester 1 · 2026–27</span><h1>Healthy connections<br /><em>create healthy outcomes.</em></h1><p>A programme view of participation, capacity, and relationship momentum.</p></div><button className="button button-outline" type="button"><Icon name="download" size={16} /> Export report</button></div>

    <div className="stat-grid analytics-stats"><div className="stat-card"><span className="stat-icon stat-icon-blue"><Icon name="users" size={18} /></span><div><span className="stat-label">Active mentorships</span><strong>128</strong><span className="stat-helper">Across 7 departments</span></div><span className="stat-trend"><Icon name="arrowUp" size={14} /> 18%</span></div><div className="stat-card"><span className="stat-icon stat-icon-green"><Icon name="trend" size={18} /></span><div><span className="stat-label">Request acceptance</span><strong>68.4%</strong><span className="stat-helper">+6.2% from last semester</span></div><span className="stat-trend"><Icon name="arrowUp" size={14} /> 6.2%</span></div><div className="stat-card"><span className="stat-icon stat-icon-amber"><Icon name="heart" size={18} /></span><div><span className="stat-label">Student satisfaction</span><strong>4.7 / 5</strong><span className="stat-helper">From 86 responses</span></div><span className="stat-trend">Strong</span></div><div className="stat-card"><span className="stat-icon stat-icon-purple"><Icon name="shield" size={18} /></span><div><span className="stat-label">Capacity health</span><strong>92%</strong><span className="stat-helper">Mentors within healthy load</span></div><span className="health-pulse" /></div></div>

    <div className="analytics-grid"><section className="panel chart-panel"><SectionHeading eyebrow="Programme growth" title="Active mentorships" action={<button className="select-button" type="button">Last 12 months <Icon name="chevron" size={14} /></button>} /><div className="chart-summary"><div><strong>128</strong><span>active relationships</span></div><span className="chart-change"><Icon name="arrowUp" size={14} /> 18.4% <small>vs previous period</small></span></div><div className="bar-chart" aria-label="Active mentorships grew over the last twelve months" role="img">{bars.map((height, index) => <div className="bar-column" key={months[index]}><span className="bar-value" style={{ height: `${height}%` }} /><small>{months[index]}</small></div>)}</div></section><section className="panel capacity-panel"><SectionHeading eyebrow="Protect mentor time" title="Capacity health" action={<button aria-label="More capacity options" className="plain-icon-button" type="button"><Icon name="more" size={18} /></button>} /><div className="capacity-gauge"><div className="gauge-dial"><strong>92<span>%</span></strong><small>healthy</small></div><div className="gauge-legend"><div><span className="legend-dot legend-green" /><span>Healthy load</span><strong>118</strong></div><div><span className="legend-dot legend-amber" /><span>Near capacity</span><strong>8</strong></div><div><span className="legend-dot legend-slate" /><span>Paused</span><strong>2</strong></div></div></div><div className="capacity-note"><Icon name="shield" size={15} /><span>Requests are being filtered before a mentor crosses their declared limit.</span></div></section></div>

    <div className="analytics-lower"><section className="panel table-panel"><SectionHeading eyebrow="Needs a closer look" title="Engagement signals" action={<button className="text-link" type="button">Open monitor <Icon name="arrow" size={15} /></button>} /><div className="signal-list"><div className="signal-row"><span className="signal-icon signal-icon-amber"><Icon name="clock" size={17} /></span><div><strong>9 relationships need a nudge</strong><span>No activity in the last 14 days</span></div><StatusBadge tone="amber">Review</StatusBadge></div><div className="signal-row"><span className="signal-icon signal-icon-green"><Icon name="check" size={17} /></span><div><strong>34 goals completed this month</strong><span>Up 22% compared to August</span></div><StatusBadge>Healthy</StatusBadge></div><div className="signal-row"><span className="signal-icon signal-icon-blue"><Icon name="people" size={17} /></span><div><strong>16 mentors ready to help</strong><span>Newly verified this semester</span></div><StatusBadge tone="blue">New</StatusBadge></div></div></section><section className="panel spotlight-panel"><span className="spotlight-mark"><Icon name="spark" size={19} /></span><span className="section-eyebrow">This semester's signal</span><h2>Small rituals are making relationships last.</h2><p>Mentorships with a shared goal in the first session are 2.4× more likely to schedule a fourth session.</p><button className="text-link" type="button">Read the insight <Icon name="arrow" size={15} /></button></section></div>
  </AppShell>;
}
